export const GET_CLIENTS = 'GET_CLIENTS';
export const SELECT_CLIENT = 'SELECT_CLIENT';
export const SELECT_CLIENT_INDEX = 'SELECT_CLIENT_INDEX';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';